[tool.poetry]
name = "llm-app"
version = "0.1.0"
description = ""
authors = ["congvmit <congvm.it@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
